// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlnxgxpvbtaycifxiikw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbnhneHB2YnRheWNpZnhpaWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDk0MzgsImV4cCI6MjA3NDUyNTQzOH0.6p6cDYUIjVjfI3it8CkwFIujUZfWy0qhh3p64J3ArBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});